### ISSUE TITLE
Vehicle owner loses access to keys after sever restart(vehicles generated by other script)

### ISSUE THREAD

**Issue by Jerrys-C** [Qbox-project/qbx_vehiclekeys#154]
### Summary

After the server restarts, vehicle owners no longer have keys to their vehicles

### Reproduction

1. Purchase a vehicle - the vehicle owner is set.
2. The owner can successfully unlock the vehicle.
3. After a server restart, the vehicle is regenerated by another plugin (persistent vehicles).
4. The player cannot unlock the vehicle, even though they are the owner.

### Expected behavior

After a server restart, the vehicle owner should retain access to the vehicle keys, allowing them to unlock and use their vehicle as expected.

### Actual behavior

Following a server restart, the player who originally purchased the vehicle is unable to unlock it, despite being the owner. This issue arises because the vehicle regeneration by another script does not retain the owner status correctly.

### Additional context

It would be beneficial to improve the logic for detecting the vehicle owner within this plugin, rather than relying solely on qbx_vehicles to set the owner state. This enhancement would help ensure consistent access for the vehicle owner, even if the owner state is not correctly set by external plugins during vehicle regeneration.

### Current Version

v1.0.1

### Custom Resources

AdvancedParking

**Comment by Manason** [comment]
Shouldn't the persistent vehicles carry over entity state?

Right now qbx_vehiclekeys makes the assumption of owner state bag being set. This does require other scripts to set vehicleid state bag if spawning a vehicle as vehicleid change handler will set the owner. If we don't make this assumption, it requires always calling back to the server and doing a database lookup to determine if the vehicle is owned.

While we have added support in other resources for vehicleid being optional, we do want to move towards a world where it is required. I'm not sure we want to make things worse for servers that handle this to help servers that do not.

**Comment by Jerrys-C** [comment]
> Shouldn't the persistent vehicles carry over entity state?
> 
> Right now qbx_vehiclekeys makes the assumption of owner state bag being set. This does require other scripts to set vehicleid state bag if spawning a vehicle as vehicleid change handler will set the owner. If we don't make this assumption, it requires always calling back to the server and doing a database lookup to determine if the vehicle is owned.
> 
> While we have added support in other resources for vehicleid being optional, we do want to move towards a world where it is required. I'm not sure we want to make things worse for servers that handle this to help servers that do not.

I completely agree that the best approach would be for the vehicle spawning script to set the state bag. However, considering that this will become a mandatory requirement, all vehicles that don’t set the state bag would fail to work. So, we can call this a secondary check. If no owner is found on the first query, a backup initialization query can be made. When creating this issue, I had also thought about this consideration—it seems it’s just a matter of whether compatibility is needed, and the decision is up to you.

**Comment by Jerrys-C** [comment]
Additionally, this modification should only take effect the first time a specific vehicle is checked—it will still prioritize checking the state bag first, then fall back to a database query if needed. If an owner is found, the state bag will be reset. The only reason I made this change is because Advanced Parking is encrypted…

**Comment by Manason** [comment]
I don't think we need to maintain backwards compatibility in this regard. In general for non qbx_core resources we don't maintain backwards compatibility as we want to move towards better approaches and not have to be stuck in the past.
