### ISSUE TITLE
no export haskeys

### ISSUE THREAD

**Issue by SKITTLE6969** [Qbox-project/qbx_vehiclekeys#31]
### Additional context

![image](https://github.com/Qbox-project/qbx_vehiclekeys/assets/92496158/fc6dd9f3-2cbe-418f-9caf-cd49f0b84432)

### Last Updated

today

### Custom Resources

none

### Resource Rename

none

**Comment by dusan01** [comment]
Change that line on qbx_core/config/client.lua line 71 to qb-vehiclekeys export, or simply use qbx_vehiclekeys instead, and you will not have that issue.
