### ISSUE TITLE
Getting a notification that i received the vehicle keys, but i did not.

### ISSUE THREAD

**Issue by domkeeeee** [Qbox-project/qbx_vehiclekeys#34]
### Summary

Getting a notification that i received the vehicle keys, but i did not.

### Reproduction

Using The Impound/Garage, or using any job garage using wasabi script, i have set up the exports correctly.

### Expected behavior

For it to give me the keys, but it just displayed a notification and didnt give me the keys

### Actual behavior

Apparently "Gave me the keys" But it seems to not work at all.

### Additional context

Video of it:
https://streamable.com/medk3o

### Last Updated

today

### Custom Resources

Nope, i only have my locales/jobs replaced, i have all latest resources of qbox.

### Resource Rename

no

**Comment by MafewTM** [comment]
Is this still an issue?

**Comment by ZKing994** [comment]
yes , this still an issue

**Comment by BerkieBb** [comment]
Should be fixed with #48

**Comment by ArturMichalak** [comment]
The fix is confirmed?

**Comment by ArturMichalak** [comment]
Feel free to re-open.
