### ISSUE TITLE
[SUGGESTIONS]

### ISSUE THREAD

**Issue by TonybynMp4** [Qbox-project/qbx_vehiclekeys#4]
### The problem

QBus copied NP even though it's dumb and really bad

### Ideal solution

Use StateBags

If car is locked and lockpick then open doors

if you own the car then you can lock/unlock

don't let vehicles turn off automatically

and a command to give the car to someone else i guess

*that's it*

**Comment by ArturMichalak** [comment]
I close, as if something is missing open it
