### ISSUE TITLE
Game Design Improvements for vehicle keys

### ISSUE THREAD

**Issue by alberttheprince** [Qbox-project/qbx_vehiclekeys#46]
### The problem

Suggesting these features be added or reworked:

qb-vehiclekeys feature set is antiquated/needs to be added to and improved.

### Ideal solution

- Proper car starting animation (depending on vehicle, motorcycle, cars, etc)
- engine start sound (most key resources don't play the full engine start up sound on restart
- give key command
- % chance world spawn cars are locked in world (config option)
- List in config of vehicles that require lockpicks to unlock (ox lib minigame)
- vehicles that require an advanced lockpick to unlock (harder minigame than the lockpick)
- List of Cars that can't be unlocked at all 
- Cars with no locks/accessible to everyone (for vehicles like wheelchairs, bicycles, etc)
- List of weapons that can and can't steal keys from drivers, with a setting for chance that some weapons are more likely 
- set change that peds will drive off: for example, 25% chance a ped tries to drive off,  10% they get and fight, 65% they give you their keys, or they try to escape
- Police alert settings: i.e. chance to alert police when lockpicking or hotwiring
- shared keys list for jobs
- Lock PD/EMS/Job vehicles automatically on leaving cars
- Config option to allow people to get into cars that are turned on and drive off
- Remote car start config option (turn off remote start as an option)
- Whitelist or "whitelist" of vehicles with no doorlocks, but need to be ox_lib circle game/lock picked to to unlock. Useful for things like motorcycles, which don't have doors but should require lockpicking.

### Alternative solutions

N/A

### Additional context

These changes would make qbx_vehiclekeys a much better resource. As it stands, qb-vehiclekeys has a pretty antiquated design and should have features added to make it more modern and useable. 

I have some of these changes in the version of qb-vehiclekeys that popcorn rp uses, although it's not the greatest implementation and most of it is janky.

**Comment by TonybynMp4** [comment]
> * Proper car starting animation (depending on vehicle, motorcycle, cars, etc)
> * engine start sound (most key resources don't play the full engine start up sound on restart)

Those two just sounds like bugs / the awful way vehiclekeys.. works

> * give key command

Fuck commands we're not NP, target option maybe?

> * % chance world spawn cars are locked in world (config option)

Yes please

> * List in config of vehicles that require lockpicks to unlock (ox lib minigame)
So a big ol' list of 95% of vehicles? 🤨 

> * shared keys list for jobs

Vehicle DB refactor + vehiclekeys rework could allow job owned vehicles 👀 

> * Lock PD/EMS/Job vehicles automatically on leaving cars

I feel like that kinda sucks, if you forget to Lock it's on you, get good bro? 🤔 

> * Config option to allow people to get into cars that are turned on and drive off

Should be a config only if we're trying to please NP fanbois, if a car is on it's on duh

> * Remote car start config option (turn off remote start as an option)

Wouldn't be a vehiclekeys thing IMO

**Comment by alberttheprince** [comment]
> Those two just sounds like bugs / the awful way vehiclekeys.. works

They're not really bugs, I think, they just need to be added in as they're not there. I'd have to check with @Manason, but we added these a long time ago and it just has to do with forcing the player to do the animations. Not sure.

I think there's a specific native for this?

> Fuck commands we're not NP, target option maybe?

Commands are good depending on the server style, not necessarily NP specific. A lot of servers use commands or are used to them. Qbox uses them for /transfervehicle for example in the vehicleshop. Would be good to have these as available options in the config. Or if you're in a vehicle.

>So a big ol' list of 95% of vehicles? 🤨

Let me clarify, it would be a list of vehicles that always start locked. So for example, police motorcycle would always spawn locked and requiring a lockpick or the rhino tank when spawned would require advanced lockpick.  Vehicles not on this list would default to the % chance world lock.

>Vehicle DB refactor + vehiclekeys rework could allow job owned vehicles 👀

it already works like this, but it's only for police/ambulance job. Better to make it something like job = police in the config, for users anyways.

>I feel like that kinda sucks, if you forget to Lock it's on you, get good bro?

Depends. For example on our server, we use the vehicle glovebox as our weapon storage for cops. So this would be useful depending on the type of server/rp level.

> Wouldn't be a vehiclekeys thing IMO (remote start)

This is already how qb-vehiclekeys work, it's always on. Would be nice to turn it off so people need to turn their car on/off when sitting in there.

**Comment by ArturMichalak** [comment]
> Proper car starting animation (depending on vehicle, motorcycle, cars, etc) 👎 

I have not found a native solution to this problem (sadly). Preparing animations for each vehicle can be too time-consuming.

> engine start sound (most key resources don't play the full engine start up sound on restart 👍 

> give key command👍 

> % chance world spawn cars are locked in world (config option) 👍 

> List in config of vehicles that require lockpicks to unlock (ox lib minigame) 👍 

> vehicles that require an advanced lockpick to unlock (harder minigame than the lockpick)

need to make a difficult mini-game

> List of Cars that can't be unlocked at all👍

> Cars with no locks/accessible to everyone (for vehicles like wheelchairs, bicycles, etc)

to do

> List of weapons that can and can't steal keys from drivers, with a setting for chance that some weapons are more likely👍

> set change that peds will drive off: for example, 25% chance a ped tries to drive off, 10% they get and fight, 65% they give you their keys, or they try to escape

need for analysis

> Police alert settings: i.e. chance to alert police when lockpicking or hotwiring

Can you describe it in more detail?

> shared keys list for jobs👍

> Lock PD/EMS/Job vehicles automatically on leaving cars

to do

> Config option to allow people to get into cars that are turned on and drive off

When getting into the vehicle, should you get the keys to it?

> Remote car start config option (turn off remote start as an option)👍

if the car is running after leaving the garage, it is set in the garages script.

> Whitelist or "whitelist" of vehicles with no doorlocks, but need to be ox_lib circle game/lock picked to to unlock. Useful for things like motorcycles, which don't have doors but should require lockpicking.👍

I marked what should be done. Most of the features should already be available, feel free to test and make comments.

**Comment by ArturMichalak** [comment]
> More specifically at the moment players can turn their engine off from a distance (they press engine off and the car will turn off or on from a distance, not sure but I think it's something like 5 meters? This should be something you can disable.

I see, qb-vehiclekeys works like this. It looks like a bug, so in qbx_vehiclekeys it is possible to start the engine while only in the vehicle. Should it be possible to start the car remotely?

> What do you need? As in you need the list? Basically just forcing players to use gun, not melee weapons to steal cars.

What I meant to say was that the chance of a ped escaping requires analysis

> List of weapons that can and can't steal keys from drivers, with a setting for chance that some weapons are more likely

Works fine

**Comment by ArturMichalak** [comment]
this branch has most of these features
https://github.com/Qbox-project/qbx_vehiclekeys/tree/renew

**Comment by alberttheprince** [comment]
> I see, qb-vehiclekeys works like this. It looks like a bug, so in qbx_vehiclekeys it is possible to start the engine only while in the vehicle. Should it be possible to start the car remotely?

I think remote on/off was unintended in qb-vehiclekeys, but I think some people do prefer this system. I don't, but always assumed it was functionality that people wanted/used.

> What I meant to say was that the chance of a ped escaping requires analysis

I think a simple break down like:

75% chance to give up, 15% chance to drive off, 10% chance to get out and fight would be dynamic enough. By giving players a chance they get injured or have to kill the driver it drives RP for other interactions like EMS, LSPD, etc.

**Comment by ArturMichalak** [comment]
> I think remote on/off was unintended in qb-vehiclekeys, but I think some people do prefer this system. I don't, but always assumed it was functionality that people wanted/used.
I would like to keep the script as simple as possible, so I would add such a feature only when needed
> I think a simple break down like
I mean it is not a simple task, depending on the native functions that you need to find

**Comment by ArturMichalak** [comment]
> Lock PD/EMS/Job vehicles automatically on leaving cars

blocked by https://github.com/overextended/ox_lib/issues/618

**Comment by ArturMichalak** [comment]
> At the moment vehicle keys will trigger when a person is hot wiring a car, not breaking into it. Change this so if someone breaks into or gets into a world vehicle they don't own there is a % chance police can be alerted.

I think it's handled

**Comment by alberttheprince** [comment]
> I mean it is not a simple task, depending on the native functions that you need to find

I think this is a feature of qb-vehicle keys already; there is a chance of the ped driving over you. I just think it doesn't actually work.

**Comment by ArturMichalak** [comment]
> I think this is a feature of qb-vehicle keys already; there is a chance of the ped driving over you. I just think it doesn't actually work.

The features that were in qb-vehiclekeys work. There is no option here to control who tries to drive off, who fights.

**Comment by alberttheprince** [comment]
> The features that were in qb-vehiclekeys work. There is no option here to control who tries to drive off, who fights.

I guess I misunderstood, I think at the moment the chance is just if the ped gives you keys or tries to drive off. I'm not sure why I thought there was a chance for them to fight you.

**Comment by ArturMichalak** [comment]
then in that case branch "renew" should have all functions

**Comment by Manason** [comment]
> then in that case branch "renew" should have all functions

Looks like it's marked as draft. Is it ready for review?

**Comment by ArturMichalak** [comment]
I think it's too complex. I will gradually upload it to the main. Functionally it should be ready to use.
