### ISSUE TITLE
feat: Remove unused functions

### ISSUE THREAD

**Issue by ArturMichalak** [Qbox-project/qbx_vehiclekeys#56]
### The problem

There are many unused functions in the resource. Maybe it's time to throw them away?

### Ideal solution

Solved lint errors.

### Additional context

![obraz](https://github.com/Qbox-project/qbx_vehiclekeys/assets/36608116/86bab95c-08a4-4281-b0c7-c904f502c0b2)

**Comment by Manason** [comment]
Sure. No need to keep dead code around when we have a git history to retrieve it if we want it back.

**Comment by ArturMichalak** [comment]
#57
