### ISSUE TITLE
[BUG] Give a vehicle keys to all players in the vehicle

### ISSUE THREAD

**Issue by ArturMichalak** [Qbox-project/qbx_vehiclekeys#60]
### The problem

At this moment it isn't possible to give the keys to everyone in the car by command.

### Ideal solution

Need to determine if we want to keep the function of giving keys to everyone in the vehicle.

**Comment by Manason** [comment]
Isn't this already the case? /givekeys will give to passengers in the vehicle if no argument is passed, no?

**Comment by ArturMichalak** [comment]
This flag is to prevent the vehicle from being locked. And it has been defined before

**Comment by ArturMichalak** [comment]
givekeys_id isn't optional argument

**Comment by Manason** [comment]
I see that you are correct. We must have introduced this regression at some point.
