### ISSUE TITLE
Toggle Engine "not possible"

### ISSUE THREAD

**Issue by Shizojin** [Qbox-project/qbx_vehiclekeys#89]
### Summary

Toggle engine not possible. After restart qbx_vehiclekeys have to be ensure again to be able to toggle engine.

### Reproduction

1. Start server
2. try toggle engine -> not working
3. ensure qbx_vehiclekeys
4. Toggle engine works again

### Expected behavior

Engine Toogle working without the need to ensure after server restart

### Actual behavior

Toggle engine not working out of the box

### Current Version

1.0.0

### Custom Resources

none

**Comment by ArturMichalak** [comment]
Please check renew branch

**Comment by ArturMichalak** [comment]
Closed due to inactivity. Fell free to reopen
