### ISSUE TITLE
spawn car not getting keys

### ISSUE THREAD

**Issue by Fraprwnt** [Qbox-project/qbx_vehiclekeys#90]
### Summary

it seems that for the latest qbx_vehiclekeys there is an error, when the car spawns there is a notification of getting the key but a 3dtext appears to search for the key.

### Reproduction

![20240726100653_1](https://github.com/user-attachments/assets/97b98b78-84ae-4c23-a66d-111729f34029)

### Expected behavior

...

### Actual behavior

...

### Additional context

....

### Current Version

renew

### Custom Resources

qbx_vehiclekeys

**Comment by Fraprwnt** [comment]
![Uploading Screenshot 2024-07-26 100354.png…]()

**Comment by Fraprwnt** [comment]
![20240726100653_1](https://github.com/user-attachments/assets/86388369-b3bf-4df3-b9df-f9747b8d980b)

**Comment by ArturMichalak** [comment]
I need reproduction steps

**Comment by ArturMichalak** [comment]
probably fixed, still need to test
